; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu -verify-machineinstrs | FileCheck %s
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu -O0 -verify-machineinstrs -o /dev/null
; RUN: llc < %s -mtriple=i686-unknown-linux-gnu -verify-machineinstrs -o /dev/null
; RUN: llc < %s -mtriple=i686-unknown-linux-gnu -no-x86-call-frame-opt -verify-machineinstrs -o /dev/null
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu -global-isel -global-isel-abort=2 \
; RUN:   -pass-remarks-missed=gisel -verify-machineinstrs -o /dev/null 2>&1 \
; RUN:   | FileCheck %s --check-prefix=GISEL

; With "x86-carry-flag-return", a trailing i1 return value is returned in the
; carry flag (used for C++ P0709 'throws' functions).

declare void @use(i64)
declare void @fill(ptr)

; Constant flags become stc/clc right before the return.
define { i64, i64, i1 } @callee(i32 %x) #0 {
; CHECK-LABEL: callee:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    # kill: def $edi killed $edi def $rdi
; CHECK-NEXT:    testl %edi, %edi
; CHECK-NEXT:    js .LBB0_1
; CHECK-NEXT:  # %bb.2: # %ok
; CHECK-NEXT:    incl %edi
; CHECK-NEXT:    clc
; CHECK-NEXT:    movq %rdi, %rax
; CHECK-NEXT:    retq
; CHECK-NEXT:  .LBB0_1: # %err
; CHECK-NEXT:    movq use@GOTPCREL(%rip), %rax
; CHECK-NEXT:    stc
; CHECK-NEXT:    movl $22, %edx
; CHECK-NEXT:    retq
entry:
  %c = icmp slt i32 %x, 0
  br i1 %c, label %err, label %ok
err:
  ret { i64, i64, i1 } { i64 ptrtoint (ptr @use to i64), i64 22, i1 true }
ok:
  %v = add i32 %x, 1
  %z = zext i32 %v to i64
  %r = insertvalue { i64, i64, i1 } poison, i64 %z, 0
  %r2 = insertvalue { i64, i64, i1 } %r, i1 false, 2
  ret { i64, i64, i1 } %r2
}

; A variable flag is set with bt.
define { i64, i64, i1 } @variable(i32 %x, i1 %f) #0 {
; CHECK-LABEL: variable:
; CHECK:       # %bb.0:
; CHECK-NEXT:    btl $0, %esi
; CHECK-NEXT:    retq
  %r = insertvalue { i64, i64, i1 } poison, i1 %f, 2
  ret { i64, i64, i1 } %r
}

; Forwarding the result is a tail call.
define { i64, i64, i1 } @forward(i32 %x) #0 {
; CHECK-LABEL: forward:
; CHECK:       # %bb.0:
; CHECK-NEXT:    jmp callee@PLT # TAILCALL
  %r = tail call { i64, i64, i1 } @callee(i32 %x) #0
  ret { i64, i64, i1 } %r
}

; No tail call if only one side returns the flag in CF.
define { i64, i64, i1 } @no_forward(i32 %x) {
; CHECK-LABEL: no_forward:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    callq callee@PLT
; CHECK-NEXT:    setb %cl
; CHECK-NEXT:    popq %rsi
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %r = tail call { i64, i64, i1 } @callee(i32 %x) #0
  ret { i64, i64, i1 } %r
}

; The caller branches on the carry flag right after the call.
define i64 @caller(i32 %x) {
; CHECK-LABEL: caller:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    callq callee@PLT
; CHECK-NEXT:    jae .LBB4_2
; CHECK-NEXT:  # %bb.1: # %err
; CHECK-NEXT:    movq %rdx, %rax
; CHECK-NEXT:    popq %rcx
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
; CHECK-NEXT:  .LBB4_2: # %ok
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    movq %rax, %rdi
; CHECK-NEXT:    callq use@PLT
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    popq %rcx
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
entry:
  %r = call { i64, i64, i1 } @callee(i32 %x) #0
  %f = extractvalue { i64, i64, i1 } %r, 2
  br i1 %f, label %err, label %ok
err:
  %e = extractvalue { i64, i64, i1 } %r, 1
  ret i64 %e
ok:
  %v = extractvalue { i64, i64, i1 } %r, 0
  call void @use(i64 %v)
  ret i64 0
}

; Without a reserved call frame, the call frame is destroyed without
; clobbering the flags.
declare { i64, i64, i1 } @stack_args(i64, i64, i64, i64, i64, i64, i64, i64) #0
define i64 @dynamic_alloca(i32 %x, i32 %n) {
; CHECK-LABEL: dynamic_alloca:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset %rbp, -16
; CHECK-NEXT:    movq %rsp, %rbp
; CHECK-NEXT:    .cfi_def_cfa_register %rbp
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_offset %rbx, -24
; CHECK-NEXT:    movq %rsp, %rbx
; CHECK-NEXT:    movl %esi, %eax
; CHECK-NEXT:    addq $15, %rax
; CHECK-NEXT:    andq $-16, %rax
; CHECK-NEXT:    subq %rax, %rbx
; CHECK-NEXT:    movq %rbx, %rsp
; CHECK-NEXT:    movl $1, %edi
; CHECK-NEXT:    movl $2, %esi
; CHECK-NEXT:    movl $3, %edx
; CHECK-NEXT:    movl $4, %ecx
; CHECK-NEXT:    movl $5, %r8d
; CHECK-NEXT:    movl $6, %r9d
; CHECK-NEXT:    pushq $8
; CHECK-NEXT:    pushq $7
; CHECK-NEXT:    callq stack_args@PLT
; CHECK-NEXT:    leaq {{[0-9]+}}(%rsp), %rsp
; CHECK-NEXT:    jae .LBB5_3
; CHECK-NEXT:  # %bb.1: # %err
; CHECK-NEXT:    movl $1, %eax
; CHECK-NEXT:    jmp .LBB5_2
; CHECK-NEXT:  .LBB5_3: # %ok
; CHECK-NEXT:    movq %rbx, %rax
; CHECK-NEXT:  .LBB5_2: # %err
; CHECK-NEXT:    leaq -8(%rbp), %rsp
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    .cfi_def_cfa %rsp, 8
; CHECK-NEXT:    retq
entry:
  %a = alloca i8, i32 %n
  %r = call { i64, i64, i1 } @stack_args(i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8) #0
  %f = extractvalue { i64, i64, i1 } %r, 2
  br i1 %f, label %err, label %ok
err:
  ret i64 1
ok:
  %p = ptrtoint ptr %a to i64
  ret i64 %p
}

; The flag is set after the stack protector check.
define { i64, i64, i1 } @stack_protector(i32 %x) #1 {
; CHECK-LABEL: stack_protector:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    subq $80, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 96
; CHECK-NEXT:    .cfi_offset %rbx, -16
; CHECK-NEXT:    movl %edi, %ebx
; CHECK-NEXT:    movq %fs:40, %rax
; CHECK-NEXT:    movq %rax, {{[0-9]+}}(%rsp)
; CHECK-NEXT:    leaq {{[0-9]+}}(%rsp), %rdi
; CHECK-NEXT:    callq fill@PLT
; CHECK-NEXT:    movq %fs:40, %rax
; CHECK-NEXT:    cmpq {{[0-9]+}}(%rsp), %rax
; CHECK-NEXT:    jne .LBB6_2
; CHECK-NEXT:  # %bb.1: # %SP_return
; CHECK-NEXT:    shrl $31, %ebx
; CHECK-NEXT:    negb %bl
; CHECK-NEXT:    leaq {{[0-9]+}}(%rsp), %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
; CHECK-NEXT:  .LBB6_2: # %CallStackCheckFailBlk
; CHECK-NEXT:    .cfi_def_cfa_offset 96
; CHECK-NEXT:    callq __stack_chk_fail@PLT
  %buf = alloca [64 x i8]
  call void @fill(ptr %buf)
  %c = icmp slt i32 %x, 0
  %r = insertvalue { i64, i64, i1 } poison, i1 %c, 2
  ret { i64, i64, i1 } %r
}

; The flag is only known on one of the paths that return the same insertvalue.
define { i64, i64, i1 } @shared_flag(i1 %c, i1 %d, i64 %v) #0 {
; CHECK-LABEL: shared_flag:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset %rbx, -16
; CHECK-NEXT:    movq %rdx, %rbx
; CHECK-NEXT:    testb $1, %dil
; CHECK-NEXT:    je .LBB7_2
; CHECK-NEXT:  # %bb.1: # %a
; CHECK-NEXT:    movl $1, %edi
; CHECK-NEXT:    callq use@PLT
; CHECK-NEXT:    stc
; CHECK-NEXT:    jmp .LBB7_4
; CHECK-NEXT:  .LBB7_2: # %b
; CHECK-NEXT:    testb $1, %sil
; CHECK-NEXT:    je .LBB7_3
; CHECK-NEXT:  # %bb.5: # %x
; CHECK-NEXT:    stc
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
; CHECK-NEXT:  .LBB7_3: # %b.ret_crit_edge
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    movzbl %dil, %eax
; CHECK-NEXT:    btl $0, %eax
; CHECK-NEXT:  .LBB7_4: # %b.ret_crit_edge
; CHECK-NEXT:    movq %rbx, %rax
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
entry:
  %r = insertvalue { i64, i64, i1 } poison, i1 %c, 2
  %r2 = insertvalue { i64, i64, i1 } %r, i64 %v, 0
  br i1 %c, label %a, label %b

a:
  call void @use(i64 1)
  br label %ret

b:
  br i1 %d, label %x, label %ret

x:
  br label %ret

ret:
  %p = phi { i64, i64, i1 } [ %r2, %a ], [ %r2, %b ], [ { i64 poison, i64 poison, i1 true }, %x ]
  ret { i64, i64, i1 } %p
}

; The callee pops its arguments; readjusting the stack must keep the flag.
declare x86_stdcallcc { i32, i32, i1 } @stdcall_callee(i32, i32) #0

define i32 @stdcall_caller(i32 %x) {
; CHECK-LABEL: stdcall_caller:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    movl %edi, %esi
; CHECK-NEXT:    callq stdcall_callee@PLT
; CHECK-NEXT:    jae .LBB8_1
; CHECK-NEXT:  # %bb.2: # %e
; CHECK-NEXT:    movl $-1, %eax
; CHECK-NEXT:    popq %rcx
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
; CHECK-NEXT:  .LBB8_1: # %ok
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    popq %rcx
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
entry:
  %r = call x86_stdcallcc { i32, i32, i1 } @stdcall_callee(i32 %x, i32 %x) #0
  %f = extractvalue { i32, i32, i1 } %r, 2
  br i1 %f, label %e, label %ok

ok:
  %v = extractvalue { i32, i32, i1 } %r, 0
  ret i32 %v

e:
  ret i32 -1
}

; GlobalISel falls back to SelectionDAG for returns (and calls) with the flag.
; GISEL: unable to translate instruction: ret{{.*}}(in function: callee)

attributes #0 = { "x86-carry-flag-return" }
attributes #1 = { sspstrong "x86-carry-flag-return" }

; Returns merged by SimplifyCFG are duplicated again, so that the flag is a
; constant for each of them (x86-carry-flag-return pass).
define { i64, i64, i1 } @merged(i32 %x) #0 {
; CHECK-LABEL: merged:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    callq callee@PLT
; CHECK-NEXT:    jae .LBB9_2
; CHECK-NEXT:  # %bb.1: # %unwind
; CHECK-NEXT:    stc
; CHECK-NEXT:    popq %rcx
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
; CHECK-NEXT:  .LBB9_2: # %cont
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    movl $1, %edi
; CHECK-NEXT:    callq use@PLT
; CHECK-NEXT:    clc
; CHECK-NEXT:    popq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
entry:
  %call = tail call { i64, i64, i1 } @callee(i32 %x) #0
  %failed = extractvalue { i64, i64, i1 } %call, 2
  br i1 %failed, label %unwind, label %cont

unwind:
  %e = insertvalue { i64, i64, i1 } %call, i1 true, 2
  br label %common.ret

common.ret:
  %r = phi { i64, i64, i1 } [ %e, %unwind ], [ { i64 poison, i64 poison, i1 false }, %cont ]
  ret { i64, i64, i1 } %r

cont:
  call void @use(i64 1)
  br label %common.ret
}

; The flag is known from the (frozen) branch condition.
define { i64, i64, i1 } @implied(i32 %x) #0 {
; CHECK-LABEL: implied:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    callq callee@PLT
; CHECK-NEXT:    jae .LBB10_1
; CHECK-NEXT:  # %bb.2: # %common.ret.split
; CHECK-NEXT:    stc
; CHECK-NEXT:    popq %rcx
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
; CHECK-NEXT:  .LBB10_1: # %select.false
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    incq %rax
; CHECK-NEXT:    clc
; CHECK-NEXT:    popq %rcx
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
entry:
  %call = tail call { i64, i64, i1 } @callee(i32 %x) #0
  %failed = extractvalue { i64, i64, i1 } %call, 2
  %v = extractvalue { i64, i64, i1 } %call, 0
  %add = add i64 %v, 1
  %ok = insertvalue { i64, i64, i1 } poison, i64 %add, 0
  %frozen = freeze i1 %failed
  br i1 %frozen, label %common.ret, label %select.false

select.false:
  br label %common.ret

common.ret:
  %pn = phi { i64, i64, i1 } [ %call, %entry ], [ %ok, %select.false ]
  %r = insertvalue { i64, i64, i1 } %pn, i1 %failed, 2
  ret { i64, i64, i1 } %r
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; GISEL: {{.*}}
